config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => "homes#about"
  devise_for :users
  resources :users, only: [:new, :create, :index, :show, :destroy, :edit, :update]
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, length: {minimum: 1, maximum:200}
  
  def get_profile_image(size)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :book_id, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :name, length: {minimum: 2, maximum: 20}, uniqueness: true
  validates :introduction, length: {maximum: 50}
  
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_one_attached :profile_image
  
  def get_profile_image(size)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/png')
    end
    profile_image.variant(resize: size).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected
  #devise利用の機能が使われる前に以下を実行←サインアップ時にnameのデータ操作を許可
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    if comment.save
      redirect_to request.referer, notice: "You have posted comment successfully"
    else
      @book = Book.find(params[:book_id])
      @user = current_user
      @book_comments = @book.book_comments.all
      @book_comment = comment
      render "books/show"
    end
  end
  
  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to request.referer, notice: "You have destroyed comment successfilly"
  end
  
  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
    @book_comments = @book.book_comments.all
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def edit
    ensure_user
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "You have destroyed book successfully."
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def ensure_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end
  
  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_user, only: [:edit, [:update]]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @book = Book.new
    @users = User.all
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def ensure_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newbook.html.erb
<!--新規投稿画面-->
  <h2>New book</h2>
  <%= form_with model: book do |f| %>
    <div class="form-group">
      <h5>Title</h5>
      <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <h5>Opinion</h5>
      <%= f.text_area :body %>
    </div>
    <div class="form-group">
      <%= f.submit "Create Book", class: "btn btn-success" %>
      </div>
  <% end %>

app/views/books/edit.html.erb
<!--books/:id/editの画面-->
<div class="container">
  <div class="row"><%= render "layouts/errors", obj: @book %></div>
  <div class="row">
    <div class="col-lg-12">
    <h1>Editing Book</h1>
    <%= form_with model: @book do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Opinion</h4>
    <%= f.text_area :body %></br>
    <span><%= f.submit "Update Book", class: "btn btn-info btn-md" %></span>
    <% end %>
    <div></br></div>

    <div>
      <%= link_to "Show", book_path, class: "btn btn-success btn-sm" %> |
      <%= link_to "Back", books_path, class: "btn btn-secondary btn-sm" %>
    </div>
    </div>
  </div>

</div>

app/views/books/index.html.erb
<!--/books画面-->
<div class="container px-5 px-sm-0">
  <%= render "layouts/errors", obj: @book %>
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: @user, book: @book %>
      <%= render "newbook", user: @user, book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <table>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
              <%= image_tag book.user.get_profile_image("80x80") %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
            <% if book.favorited_by?(current_user) %>
            <td>
              <%= link_to book_favorites_path(book), method: :delete do %>
                <i class="fas fa-heart" style="color: #ea542e;"><%= book.favorites.count %></i>
              <% end %>
            </td>
            <% else %>
            <td>
              <%= link_to book_favorites_path(book), method: :post do %>
                <i class="fas fa-heart"><%= book.favorites.count %></i>
              <% end %>
            </td>
            <% end %>
            <td>
              コメント数：<%= book.book_comments.count %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<!--/books/:idの画面-->
<div class="row"><%= render "layouts/errors", obj: @book %></div>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: @user, book: @book %>
      <%= render "newbook", book: Book.new %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h4>Book detail</h4>
      <table>
        <tbody>
          <td>
            <%= link_to user_path(@book.user.id) do %>
              <%= image_tag @book.user.get_profile_image("80x80") %>
              <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book_path %></td>
          <td><%= @book.body %></td>
          <% if @book.favorited_by?(current_user) %>
          <td>
            <%= link_to book_favorites_path(@book), method: :delete do %>
              <i class="fas fa-heart" style="color: #ea542e;"><%= @book.favorites.count %></i>
            <% end %>
          </td>
          <% else %>
          <td>
            <%= link_to book_favorites_path(@book), method: :post do %>
              <i class="fas fa-heart"><%= @book.favorites.count %></i>
            <% end %>
          </td>
          <% end %>
          <% if @book.user == current_user %>
            <td><%= link_to "Edit", edit_book_path, class: "btn btn-info btn-sm" %></td>
            <td><%= link_to "Destroy", book_path, method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-danger btn-sm" %></td>
          <% end %>
          <td>
            コメント数：<%= @book.book_comments.count %>
          </td>
        </tbody>
      </table>
      <table>
      <% @book_comments.each do |comment| %>
        <tbody>
        <tr>コメント一覧</tr>
        <tr>
          <td>
          <%= link_to user_path(comment.user.id) do %>
            <%= image_tag comment.user.get_profile_image("80x80") %></br>
            <%= comment.user.name %>
          <% end %>
          </td>
          <td>
            <%= comment.comment %>
          </td>
          <td>
          <% if current_user == comment.user %>
            <%= link_to "Destroy", book_book_comment_path(comment.book, comment), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-danger btn-sm" %>
          <% end %>
          </td>
        </tr>
        </tbody>
      <% end %>
      </table>
      <%= form_with model: [@book, @book_comment] do |f| %>
        <div class="form-group">
          <h5>コメント入力</h5>
          <%= f.text_area :comment, rows: '5' %></br>
          <%= f.submit "送信", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="raw">
    <h1 class="col-md-12 px-3 mx-auto">
      Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>In <strong>Bookers</strong>, <br/></p>
      <p>you can share and exchange your opinions, inpressions, and emotions<br/></p>
      <p>about various books!</p>
    </div>

    <div class="btn-wrapper col-10 mx-auto">
      <div class="row">
        <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
      </div>
      <div class="row">
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h2><%= obj.errors.count %> errors prohobited this object from being saved.</h2>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/6434279763.js" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar brand p-3 text-light btn btn-lg" href="/">
            Bookers
          </a>
          <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-expanded="false" aria-label="Togle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse" id="navbarNavDropdown" style>
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li>
              <%=  link_to users_path,class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> Users
              <% end %>
            </li>
            <li>
              <%=  link_to books_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> Books
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> Log out
              <% end %>
            </li>
            <% else %>
            <li>
              <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li>
              <%= link_to home_about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> About
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> Sign up
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> Log in
              <% end %>
            </li>
            <% end %>
          </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <p id="notice"><%= flash[:notice] %></p>
      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/_info.html.erb
<!--部分テンプレート　User info-->
<div>
  <h2>User info</h2>

  <!--ここに画像を追加-->
  <p><%= image_tag user.get_profile_image("100x100") %></p>

  <table class="table">
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </table>

  <!--ユーザー編集画面へ遷移-->
  <div class="row">
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<!--edit_userの画面-->
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h1>User info</h1>
    <%= render "layouts/errors", obj: @user %>
    <%= form_with model: @user, local:true do |f| %>
    <h4>name</h1>
    <%= f.text_field :name %>
    <h4>Image</h4>
    <%= f.file_field :profile_image, accept: "image/*" %>
    <h4>Introduction</h4>
    <%= f.text_area :introduction %></br>
    <%= f.submit "Update User" %>
    <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<!--/usersの画面-->
<h1>This page is users/index page</h1>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "info", user: current_user, book: @book %>
      <%= render "books/newbook", book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table>
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= link_to user_path(user.id) do %>
              <%= image_tag user.get_profile_image("80x80") %>
              <% end %>
            </td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id), class: "btn btn-info btn-sm" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!--/users/:idの画面-->
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "info", user: @user, book: @book %>
      <%= render "books/newbook", book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <table>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
              <%= image_tag book.user.get_profile_image("80x80") %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
            <% if book.favorited_by?(current_user) %>
            <td>
              <%= link_to book_favorites_path(book), method: :delete do %>
                <i class="fas fa-heart" style="color: #ea542e"><%= book.favorites.count %></i>
              <% end %>
            </td>
            <% else %>
            <td>
              <%= link_to book_favorites_path(book), method: :post do %>
                <i class="fas fa-heart"><%= book.favorites.count %></i>
              <% end %>
            </td>
            <td>
              コメント数：<%= book.book_comments.count %>
            </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>